[package]
name = "fzf-git"
version = "0.1.0"
authors = ["Andy Fang <andy.fang@airbnb.com>"]
edition = "2018"

[dependencies]
git2 = "0.8"
failure = "0.1.5"
quicli = "0.4"
structopt = "0.2"
hex = "0.3.2"
chrono = "0.4.6"
itertools = "0.8.0"
tabwriter = "1.1.0"